### ISSUE TITLE
Bronya's Planar Sphere main attribute

### ISSUE THREAD

**Issue by yeci226** [Mar-7th/StarRailScore#1]
AttackAddedRatio: 0.8 -> 0
WindAddedRatio: 0.8 -> 0

HPAddedRatio: 0 -> 1
DefenceAddedRatio: 0 -> 0.8 or 1

Because Bronya is not mainly attacking, but protecting self while strengthening his teammates

**Comment by mobyw** [comment]
Bronya's Basic ATK has a 100% CRIT RATE, can also provide one-target damage.

Here is the config of relic recommend:

```json
"1101": {
  "AvatarID": 1101,
  "Set4IDList": [102, 110, 101],
  "Set2IDList": [302, 308, 307],
  "PropertyList": [
    { "RelicType": "BODY", "PropertyType": "CriticalDamageBase" },
    { "RelicType": "FOOT", "PropertyType": "SpeedDelta" },
    { "RelicType": "NECK", "PropertyType": "WindAddedRatio" },
    { "RelicType": "OBJECT", "PropertyType": "SPRatioBase" }
  ]
}
```

**Comment by mobyw** [comment]
The damage and survival config of auxiliary characters needs to be adjusted, this will be changed together later.

**Comment by mobyw** [comment]
Fixed in recent commits.
