### ISSUE TITLE
请求更新2.1角色遗器评分标准

### ISSUE THREAD

**Issue by QSlotus** [Mar-7th/StarRailScore#2]
如题
还有，这个评分标准是根据啥来的，想提pr但是不知道怎么弄🥺

**Comment by mobyw** [comment]
副词条推荐根据社区攻略配置，主词条推荐根据游戏内推荐算法结合社区攻略配置。由于大部分角色比较依赖于机制，所以都是手工整理。

新增时可以结合相同命途或元素的其他角色来配置系数，根据角色机制做调整。

**Comment by ShikiSuen** [comment]
@mobyw 知更鸟与同谐主的评分这样搞可以吗？

```

        "8006": .init(
            main: [
                .body: [:],
                .foot: [
                    .spdDelta: .highest,
                ],
                .object: [:],
                .neck: [
                    .energyRecovery: .highest,
                    .breakDmg: .higherPlus,
                ],
            ],
            weight: [
                .breakDmg: .highest,
                .spdDelta: .highest,
                .defAmp: .higher,
                .defDelta: .high,
                .hpAmp: .higher,
                .hpDelta: .high,
            ],
            max: 10.0
        ),
        "1309": .init(
            main: [
                .body: [.atkAmp: .highest],
                .foot: [.atkAmp: .highest],
                .object: [.atkAmp: .highest],
                .neck: [.energyRecovery: .highest],
            ],
            weight: [
                .spdDelta: .highest,
                .atkAmp: .higher,
                .atkDelta: .highPlus,
                .hpAmp: .higher,
                .hpDelta: .highPlus,
                .defAmp: .higher,
                .defDelta: .highPlus,
            ],
            max: 10.0
        ),
```

**Comment by mobyw** [comment]
2.2 数据已更新

**Comment by ShikiSuen** [comment]
> 2.2 数据已更新

请问 Boothill 的圣遗物副词条权重怎么都是 0？
https://github.com/Mar-7th/StarRailScore/blob/933d70bacf01baec52794c34639475bb09b57601/score.json#L2819-L2830

**Comment by QSlotus** [comment]
还没实装呢（）
要下半去了

________________________________

**Comment by ShikiSuen** [comment]
这套评定数据可能需要再审一审。
托帕的有效词条里面居然把击破特攻的权重设为 0 就有点费解了：
（Bilibili 百科居然也没把这个词条的权重考虑进去。）

https://github.com/Mar-7th/StarRailScore/blob/933d70bacf01baec52794c34639475bb09b57601/score.json#L1182-L1240

**Comment by mobyw** [comment]
> 这套评定数据可能需要再审一审。 托帕的有效词条里面居然把击破特攻的权重设为 0 就有点费解了

副词条评分采用的角色推出时的主流组队方式，角色定位会随新角色和机制的出现而发生改变。

> （Bilibili 百科居然也没把这个词条的权重考虑进去。）

就当前环境而言，普遍认为击破特攻是无效词条。即使是有相关机制增益的角色，如果使用了击破特攻主词条的遗器，副词条堆击破特攻收益也不如攻击与暴击暴伤。目前仅同谐开拓者有对击破特攻机制进行优化，可以达到较高的击破特攻收益。

**Comment by ShikiSuen** [comment]
@mobyw 我调整了一下波提欧的评分模型：https://github.com/Mar-7th/StarRailScore/pull/3

**Comment by ShikiSuen** [comment]
@mobyw 2.6 的角色的评分模型好像还没更新的样子。

**Comment by JT921111** [comment]
May I ask when will it update to version 2.7 or even 3.0?

**Comment by mobyw** [comment]
> May I ask when will it update to version 2.7 or even 3.0?

the weights are now set manually, cuz a delay in updating

we are currently working on extracting in-game recommendation for automatic updating by actions

**Comment by JT921111** [comment]
Thanks for your reply.
Looking forward for the updates.
